In [1]:
import pandas as pd
import numpy as np

In [2]:
df_base = pd.read_csv("isef-database.csv")
df_base.head()

,id,title,category,year,schools,abstract,country,State,Province,awards
0,13327,Distribution and Patterns of Movement of the W...,Plant Sciences,2014,set(),Because a previously identified male pheromone...,United States of America,FL,NaN,['Intel Foundation Cultural and Scientific Vis...
1,13493,The Use of Quantitative PCR to Determine the I...,Plant Sciences,2014,set(),Danio rerio are tropical transgenic zebrafish ...,United States of America,MN,NaN,['nan']
2,13649,Evaluation of Physiological Conditions that In...,Biomedical and Health Sciences,2014,set(),The purpose of this experiment was to find out...,United States of America,AR,NaN,['nan']
3,13712,Autism in Fruit Flies II: Behavior of Drosophi...,Plant Sciences,2014,set(),The study of genetic variations that cause aut...,United States of America,OH,NaN,['nan']
4,13269,Environmentally Induced Epigenetic Transgenera...,Plant Sciences,2014,set(),Environmental factors have a significant impac...,United States of America,OK,NaN,['nan']

In [3]:
df = df_base.copy()

In [4]:
df.shape

(16244, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16244 entries, 0 to 16243
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        16244 non-null  int64
 1   title     16244 non-null  object
 2   category  14184 non-null  object
 3   year      16244 non-null  int64
 4   schools   16244 non-null  object
 5   abstract  12840 non-null  object
 6   country   15467 non-null  object
 7   State     10317 non-null  object
 8   Province  1659 non-null   object
 9   awards    15467 non-null  object
dtypes: int64(2), object(8)
memory usage: 1.2+ MB

In [6]:
df["country"].unique()

array(['United States of America', 'Japan', 'American Samoa',
       'United States Virgin Islands', 'India', 'China',
       'Russian Federation', 'Puerto Rico', 'Thailand', 'Australia',
       'Kuwait', 'Jordan', 'Mexico', 'South Africa', nan, 'Saudi Arabia',
       'Canada', 'Estonia', 'Lebanon', 'Colombia', 'Finland', 'Turkey',
       'Romania', 'Uruguay', 'Qatar', 'Oman', 'Brazil', 'Czech Republic',
       'Israel', 'Sri Lanka', 'Switzerland', 'Egypt', 'Slovakia', 'Chile',
       'Chinese Taipei', 'Italy', 'Ukraine', 'Panama', 'Guam',
       'Singapore', 'South Korea', 'Azerbaijan', 'Denmark', 'Malaysia',
       'Poland', 'Germany',
       'China, Hong Kong Special Administrative Region', 'Kenya',
       'Viet Nam', 'United Arab Emirates', 'Belarus',
       'Republic of Moldova', 'Tunisia', 'Northern Mariana Islands',
       'Sweden', 'Palestine', 'Austria',
       'China, Macao Special Administrative Region', 'Peru', 'Iraq',
       'Norway', 'Hungary', 'Northern Ireland', 'United Kingdom',
       'Pakistan', 'Ireland', 'Costa Rica', 'Indonesia', 'Portugal',
       'Nigeria', 'Argentina', 'Philippines', 'Georgia', 'Netherlands',
       'France', 'Kazakhstan', 'Spain', 'Bulgaria', 'New Zealand',
       'Luxembourg', 'Slovenia', 'Bangladesh', 'Belgium', 'Zimbabwe',
       'Ghana', 'Latvia', 'Guatemala', 'Taiwan', 'Haiti', 'Greece',
       'Armenia', 'Venezuela'], dtype=object)

In [7]:
df[(df["country"] == "Turkey") & (df["schools"].str.contains("Ataturk"))]

,id,title,category,year,schools,abstract,country,State,Province,awards
6062,14753,RDS of Things: Using RDS Technology for Smart ...,Embedded Systems,2018,{'Ankara Ataturk Lisesi'},Living in big cities is getting harder every d...,Turkey,NaN,NaN,['K. Soumyanath Memorial Award: First Award of...
7587,17362,Kabartgac: An Electronic Ring that Helps Visua...,Biomedical Engineering,2019,{'Izmir Ataturk High School'},This project aims to allow visually impaired p...,Turkey,NaN,NaN,['nan']
13386,23192,Teach Me Braille: A Kit Consisting of Modules ...,Robotics and Intelligent Machines,2023,{'Ataturk High School of Science'},NaN,Turkey,NaN,NaN,"['Third Award of $1,000']"
13455,23194,A Novel Passive Positioning System Based on Wa...,Systems Software,2023,{'Ataturk High School of Science'},NaN,Turkey,NaN,NaN,['nan']
14082,24741,A Mesh Network-Integrated Multi-Robot Team Wit...,Embedded Systems,2024,{'Ataturk High School of Science'},NaN,Turkey,NaN,NaN,['U.S. Agency for International Development: S...
15581,26065,Degradation of Polyethylene Terephthalate (PET...,Environmental Engineering,2025,{'Izmir Ataturk High School'},Polyethylene Terephthalate (PET) has become on...,Turkey,NaN,NaN,['nan']

In [8]:
df[(df["country"] == "Turkey") & (df["schools"]== "{'Ataturk High School of Science'}")]

,id,title,category,year,schools,abstract,country,State,Province,awards
13386,23192,Teach Me Braille: A Kit Consisting of Modules ...,Robotics and Intelligent Machines,2023,{'Ataturk High School of Science'},NaN,Turkey,NaN,NaN,"['Third Award of $1,000']"
13455,23194,A Novel Passive Positioning System Based on Wa...,Systems Software,2023,{'Ataturk High School of Science'},NaN,Turkey,NaN,NaN,['nan']
14082,24741,A Mesh Network-Integrated Multi-Robot Team Wit...,Embedded Systems,2024,{'Ataturk High School of Science'},NaN,Turkey,NaN,NaN,['U.S. Agency for International Development: S...

In [9]:
df.drop("Province",inplace = True, axis = 1)

In [10]:
df

,id,title,category,year,schools,abstract,country,State,awards
0,13327,Distribution and Patterns of Movement of the W...,Plant Sciences,2014,set(),Because a previously identified male pheromone...,United States of America,FL,['Intel Foundation Cultural and Scientific Vis...
1,13493,The Use of Quantitative PCR to Determine the I...,Plant Sciences,2014,set(),Danio rerio are tropical transgenic zebrafish ...,United States of America,MN,['nan']
2,13649,Evaluation of Physiological Conditions that In...,Biomedical and Health Sciences,2014,set(),The purpose of this experiment was to find out...,United States of America,AR,['nan']
3,13712,Autism in Fruit Flies II: Behavior of Drosophi...,Plant Sciences,2014,set(),The study of genetic variations that cause aut...,United States of America,OH,['nan']
4,13269,Environmentally Induced Epigenetic Transgenera...,Plant Sciences,2014,set(),Environmental factors have a significant impac...,United States of America,OK,['nan']
...,...,...,...,...,...,...,...,...,...
16239,27397,Discovery of Novel Self-Antigens in IgG4-Relat...,Translational Medical Science,2025,{'Montgomery Blair High School'},"Autoimmune diseases affect millions worldwide,...",United States of America,MD,['nan']
16240,27283,An End-to-End AI Hardware Solution for Ophthal...,Translational Medical Science,2025,{'The Lawrenceville School'},The prevalence of diseases such as diabetic re...,United States of America,NJ,['nan']
16241,26981,MRI SmarT: A Novel Multi-Modal Approach to Tum...,Translational Medical Science,2025,"{'Miramonte High School', 'The Harker School'}",NaN,United States of America,CA,['nan']
16242,27224,Optimization of Lipid Nanoparticle Formulation...,Translational Medical Science,2025,{'Pine Crest School'},Osteoarthritis (OA) is a chronic inflammatory ...,United States of America,FL,['nan']
16243,27478,Colorectal Cancer Imaging and Classification -...,Translational Medical Science,2025,{'Sunset High School'},Colorectal cancer is the second leading cause ...,United States of America,OR,['nan']

In [11]:
def clean_school(val):
    if pd.isna(val):
        return np.nan
    try:
        val = str(val)
        val = val.replace("{","").replace("}","").strip()
        return val
    except:
        return np.nan

In [12]:
df["schools"] = df["schools"].apply(clean_school)

In [13]:
len(df[df["schools"] == "set()"])

5544

In [14]:
df.drop("State",axis = 1, inplace = True)

In [15]:
df.head()

,id,title,category,year,schools,abstract,country,awards
0,13327,Distribution and Patterns of Movement of the W...,Plant Sciences,2014,set(),Because a previously identified male pheromone...,United States of America,['Intel Foundation Cultural and Scientific Vis...
1,13493,The Use of Quantitative PCR to Determine the I...,Plant Sciences,2014,set(),Danio rerio are tropical transgenic zebrafish ...,United States of America,['nan']
2,13649,Evaluation of Physiological Conditions that In...,Biomedical and Health Sciences,2014,set(),The purpose of this experiment was to find out...,United States of America,['nan']
3,13712,Autism in Fruit Flies II: Behavior of Drosophi...,Plant Sciences,2014,set(),The study of genetic variations that cause aut...,United States of America,['nan']
4,13269,Environmentally Induced Epigenetic Transgenera...,Plant Sciences,2014,set(),Environmental factors have a significant impac...,United States of America,['nan']

In [16]:
df["year"].unique()

array([2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024,
       2025])

In [18]:
df["awards"].unique()

array(["['Intel Foundation Cultural and Scientific Visit to China Award']",
       "['nan']", nan, ...,
       "['Missouri University of Science and Technology: Summer Camp scholarships (camp tuition and travel expenses, valued at up to $1,500) Missouri University of Science and Technology: Summer Camp scholarships (camp tuition and travel expenses, valued at up to $1,500)']",
       "['Third Award of $1,000 Mary Kay Inc.: First Prize']",
       "['Second Award of $2,000 NASA: 1st Prize']"], dtype=object)

In [19]:
def clean_nan(val):
    if pd.isna(val):
        return np.nan
    val = str(val)
    val = val.replace("[","").replace("]","").strip()
    if "nan" in val:
        return np.nan
    return val

In [20]:
df["awards"] = df["awards"].apply(clean_nan)
df.head()

,id,title,category,year,schools,abstract,country,awards
0,13327,Distribution and Patterns of Movement of the W...,Plant Sciences,2014,set(),Because a previously identified male pheromone...,United States of America,'Intel Foundation Cultural and Scientific Visi...
1,13493,The Use of Quantitative PCR to Determine the I...,Plant Sciences,2014,set(),Danio rerio are tropical transgenic zebrafish ...,United States of America,NaN
2,13649,Evaluation of Physiological Conditions that In...,Biomedical and Health Sciences,2014,set(),The purpose of this experiment was to find out...,United States of America,NaN
3,13712,Autism in Fruit Flies II: Behavior of Drosophi...,Plant Sciences,2014,set(),The study of genetic variations that cause aut...,United States of America,NaN
4,13269,Environmentally Induced Epigenetic Transgenera...,Plant Sciences,2014,set(),Environmental factors have a significant impac...,United States of America,NaN

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16244 entries, 0 to 16243
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        16244 non-null  int64
 1   title     16244 non-null  object
 2   category  14184 non-null  object
 3   year      16244 non-null  int64
 4   schools   16244 non-null  object
 5   abstract  12840 non-null  object
 6   country   15467 non-null  object
 7   awards    4457 non-null   object
dtypes: int64(2), object(6)
memory usage: 1015.4+ KB

In [27]:
def clean_schools(val):
    if pd.isna(val):
        return np.nan
    if ("set" in val) and (isinstance(val,str)):
        return np.nan

In [28]:
df["schools"] = df["schools"].apply(clean_schools)
df.head()

,id,title,category,year,schools,abstract,country,awards
0,13327,Distribution and Patterns of Movement of the W...,Plant Sciences,2014,NaN,Because a previously identified male pheromone...,United States of America,'Intel Foundation Cultural and Scientific Visi...
1,13493,The Use of Quantitative PCR to Determine the I...,Plant Sciences,2014,NaN,Danio rerio are tropical transgenic zebrafish ...,United States of America,NaN
2,13649,Evaluation of Physiological Conditions that In...,Biomedical and Health Sciences,2014,NaN,The purpose of this experiment was to find out...,United States of America,NaN
3,13712,Autism in Fruit Flies II: Behavior of Drosophi...,Plant Sciences,2014,NaN,The study of genetic variations that cause aut...,United States of America,NaN
4,13269,Environmentally Induced Epigenetic Transgenera...,Plant Sciences,2014,NaN,Environmental factors have a significant impac...,United States of America,NaN

In [40]:
df.groupby("category")["awards"].count()

category
Animal Sciences                               133
Behavioral and Social Sciences                189
Biochemistry                                   89
Biomedical Engineering                        244
Biomedical and Health Sciences                193
Cellular and Molecular Biology                117
Chemistry                                     203
Computational Biology and Bioinformatics      169
Earth and Environmental Sciences              256
Embedded Systems                              146
Energy: Chemical                               71
Energy: Physical                               62
Energy: Sustainable Materials and Design      132
Engineering Mechanics                         134
Engineering Technology: Statics & Dynamics     83
Environmental Engineering                     237
Materials Science                             109
Mathematics                                   192
Microbiology                                  156
Physics and Astronomy                         211
Plant Sciences                                142
Robotics and Intelligent Machines             230
Systems Software                              213
Technology Enhances the Arts                    7
Translational Medical Science                 182
Name: awards, dtype: int64

In [38]:
df.isnull().sum()

id              0
title           0
category     2060
year            0
schools     16244
abstract     3404
country       777
awards      11787
dtype: int64

In [41]:
df[df["id"].duplicated(keep=False)].sort_values("id")

,id,title,category,year,schools,abstract,country,awards
4357,5648,Potential Therapeutic Effect of Novel Multivit...,Biomedical and Health Sciences,2017,NaN,The objective of this study was to re-measure ...,Egypt,NaN
4356,5648,Potential Therapeutic Effect of Novel Multivit...,Biomedical and Health Sciences,2017,NaN,The objective of this study was to re-measure ...,Egypt,NaN
5377,8956,Safecopter: Developing a Collision Avoidance S...,Robotics and Intelligent Machines,2017,NaN,Multicopters have a wide range of applications...,United States of America,"'Third Award of $1,000 Air Force Research Labo..."
5376,8956,Safecopter: Developing a Collision Avoidance S...,Robotics and Intelligent Machines,2017,NaN,Multicopters have a wide range of applications...,United States of America,"'Third Award of $1,000'"
3258,10718,Two Transistor Ternary Random Access Memory,NaN,2016,NaN,The limitation of the speed of a computer is t...,United States of America,NaN
...,...,...,...,...,...,...,...,...
14080,24801,Giving Robot Hands a Feeling,Embedded Systems,2024,NaN,Grasping is a critical function for human-like...,United States of America,NaN
16083,26031,Novel Approach to Calculation of Bike Route Di...,Systems Software,2025,NaN,A fractal is a mathematical object with non-in...,United States of America,'Air Force Research Laboratory on behalf of th...
16084,26031,Novel Approach to Calculation of Bike Route Di...,Systems Software,2025,NaN,A fractal is a mathematical object with non-in...,United States of America,NaN
15411,26293,Giving Robot Hands a Feeling,Embedded Systems,2025,NaN,Background: Grasping is a critical function fo...,United States of America,NaN
15412,26293,Giving Robot Hands a Feeling,Embedded Systems,2025,NaN,Background: Grasping is a critical function fo...,United States of America,NaN

In [46]:
print(df.loc[5376,"awards"])
print("-------------------------------------------------------")
print(df.loc[5377,"awards"])

'Third Award of $1,000'
-------------------------------------------------------
'Third Award of $1,000 Air Force Research Laboratory on behalf of the United States Air Force: First Award of $750 in each Intel ISEF Category Society of Experimental Test Pilots: Certificate of Honorable Mention NASA: Second Award of $750'

In [47]:
df[df["title"].duplicated(keep=False)].sort_values("title")

,id,title,category,year,schools,abstract,country,awards
3403,11271,A Nanomedicine Approach for Targeted Thrombolysis,NaN,2016,NaN,In thrombo-occlusive vascular pathologies like...,United States of America,NaN
3404,11271,A Nanomedicine Approach for Targeted Thrombolysis,NaN,2016,NaN,In thrombo-occlusive vascular pathologies like...,United States of America,NaN
1738,12386,A Nanomedicine Approach for Targeted Thrombolysis,NaN,2015,NaN,In occlusive vascular pathologies like heart a...,United States of America,NaN
1737,12386,A Nanomedicine Approach for Targeted Thrombolysis,NaN,2015,NaN,In occlusive vascular pathologies like heart a...,United States of America,NaN
11557,23148,A Novel Approach to Early Directional Diagnosi...,Biomedical Engineering,2022,NaN,Prescription opioid addiction is a national he...,United States of America,NaN
...,...,...,...,...,...,...,...,...
467,13405,Two Transistor Ternary Random Access Memory,Energy: Chemical,2014,NaN,The limitation of the speed of a computer is t...,United States of America,NaN
2498,12726,Using Aliivibrio fischeri to Detect Water Toxins,NaN,2015,NaN,Conventional water analysis typically makes it...,United States of America,NaN
2497,12726,Using Aliivibrio fischeri to Detect Water Toxins,NaN,2015,NaN,Conventional water analysis typically makes it...,United States of America,NaN
1195,13887,Using Aliivibrio fischeri to Detect Water Toxins,Robotics and Intelligent Machines,2014,NaN,"Aliivibrio Fischeri is a very effective, econo...",United States of America,NaN
1194,13887,Using Aliivibrio fischeri to Detect Water Toxins,Robotics and Intelligent Machines,2014,NaN,"Aliivibrio Fischeri is a very effective, econo...",United States of America,NaN

In [48]:
df["id"].duplicated().sum()

np.int64(45)

In [49]:
df["title"].duplicated().sum()

np.int64(66)

In [55]:
dup = df[df["id"].duplicated(keep=False)].sort_values("id")
dup.groupby("id").nunique().sort_values("awards", ascending=False)

       title  category  year  schools  abstract  country  awards
id
22226      1         1     1        0         1        1       2
11309      1         0     1        0         1        1       2
8956       1         1     1        0         1        1       2
12147      1         0     1        0         1        1       2
24663      1         1     1        0         1        1       2
16195      1         1     1        0         0        1       2
16041      1         1     1        0         1        1       2
23422      1         1     1        0         1        1       2
13405      1         1     1        0         1        1       1
19415      1         1     1        0         1        1       1
18695      1         1     1        0         1        1       1
17752      1         1     1        0         1        1       1
16670      1         1     1        0         1        1       1
19483      1         1     1        0         1        1       1
23148      1         1     1        0         1        1       1
12710      1         0     1        0         1        1       1
24644      1         1     1        0         1        1       1
26031      1         1     1        0         1        1       1
11214      1         0     1        0         1        1       1
10718      1         0     1        0         1        1       1
20135      1         1     1        0         1        1       0
22336      1         1     1        0         1        1       0
21913      1         1     1        0         1        1       0
23645      1         1     1        0         1        1       0
24801      1         1     1        0         1        1       0
21613      1         1     1        0         1        1       0
20644      1         1     1        0         0        1       0
5648       1         1     1        0         1        1       0
17671      1         1     1        0         1        1       0
19238      1         1     1        0         0        1       0
19055      1         1     1        0         1        1       0
15385      1         1     1        0         1        1       0
14427      1         1     1        0         1        1       0
13887      1         1     1        0         1        1       0
13232      1         0     1        0         1        1       0
12726      1         0     1        0         1        1       0
12519      1         0     1        0         1        2       0
12518      1         0     1        0         0        2       0
12386      1         0     1        0         1        1       0
11519      1         1     1        0         1        1       0
11271      1         0     1        0         1        1       0
26293      1         1     1        0         1        1       0

In [57]:
dup_awards = dup.groupby("id")["awards"].nunique()

dup_awards[dup_awards > 1]

id
8956     2
11309    2
12147    2
16041    2
16195    2
22226    2
23422    2
24663    2
Name: awards, dtype: int64

In [59]:
df = df.drop_duplicates(subset="id", keep="first")

In [60]:
df.shape

(16199, 8)

In [61]:
df.isnull().sum()

id              0
title           0
category     2049
year            0
schools     16199
abstract     3400
country       777
awards      11759
dtype: int64